"""Comparing relationships of numbers using bool."""
__author__ = "730396516"
left = int(input("Left-hand side: "))
right = int(input("Right-hand side: "))
less_than = int(left < right)
less_than_bool = bool(less_than)
string_left = str(left)
string_right = str(right)
string_less_than_bool = str(less_than_bool)
print(string_left + " < " + string_right + " is " + string_less_than_bool)
greater_or_equal = int(left >= right)
greater_or_equal_bool = bool(greater_or_equal)
string_greater_or_equal_bool = str(greater_or_equal_bool)
print(string_left + " >= " + string_right + " is " + string_greater_or_equal_bool)
equal = int(left == right)
equal_bool = bool(equal)
string_equal_bool = str(equal_bool)
print(string_left + " == " + string_right + " is " + string_equal_bool)
not_equal = int(left != right)
not_equal_bool = bool(not_equal)
string_not_equal_bool = str(not_equal_bool)
print(string_left + " != " + string_right + " is " + string_not_equal_bool)